#!/bin/bash

cat << FIM

Para finalizar a gravação do terminal:

1. Pressione as teclas CTRL+D;
2. Pressione a tecla ENTER para confirmar a publicação da gravação;
3. Anote o ID (identificador) da gravação.

FIM

read -p "Título: " titulo
asciinema rec -i 2.5 -t "${titulo}"

