#!/usr/bin/env python3

from subprocess import run

LABS = ['1', '2', '3', '4', 'redes']
CONF_FILE = '/etc/network/interfaces.d/enp0s10'
IFACE_DOWN = '/usr/sbin/ifdown'
IFACE_UP = '/usr/sbin/ifup'

print("Informe o laboratório (Ex.: 1, 2, 3, 4 ou redes) e o número de seu PC (Ex.: 1, 2, ..., 40).")
lab = input('Número ou nome do laboratório: ')
while lab not in LABS:
    print("Informe o laboratório (Ex.: 1, 2, 3, 4 ou redes) e o número de seu PC (Ex.: 1, 2, ..., 40).")
    lab = input('Número ou nome do laboratório: ')

pc = input("Número de seu PC: ")
while not pc.isdigit() and int(pc)>0:
    pc = input("Número de seu PC: ")
    
# Remove zeros à esquerda
pc = str(int(pc))

if lab=='redes':
    rede_ipv4 = '172.16.1.1'
else:
    rede_ipv4 = f'10.209.10{lab}.'

end_ipv4 = f'{rede_ipv4}{pc.zfill(2)}/16'

with open(file=CONF_FILE, mode='w', encoding='utf-8') as conf_file_enp0s10:
    conf = f'''\
allow-hotplug enp0s10
iface enp0s10 inet static
  address {end_ipv4}
'''
    conf_file_enp0s10.write(conf)
    run([IFACE_DOWN, 'enp0s10'])
    run([IFACE_UP, 'enp0s10'])
