#!/bin/bash

echo "Atualizando os scripts de Jurandy..."

if [ "$UID" -ne 0 ]; then
    echo "ERRO: O script \"${0}\" deve ser executado pelo usuário \"root\" ou via comando \"sudo\"."
    exit 1
fi

cd /usr/local/bin
git fetch
git merge
