#!/usr/bin/env python3

import shlex
import sys

hist_entry = sys.stdin.readline()

while len(hist_entry) > 1:
    hist_index,cmd_line = shlex.split(hist_entry, comments=True)    
    hist_entry = sys.stdin.readline()
